import { describe, expect, it } from 'vitest';
import { generateClaudeMd } from '../claude-md-generator.js';
import type { GeneratorContext } from '../types.js';

function fullContext(): GeneratorContext {
  return {
    generator_version: '1.0.0',
    domain_id: 'development-agent',
    constitution: {
      schema_version: 'constitution.v1',
      generated_at: '2026-01-01T00:00:00.000Z',
      generator_version: '1.0.0',
      user_scope: 'single_user',
      principles: [
        { id: 'clarity', statement: 'Prioritize clarity', priority: 1, applies_to: ['*'] },
      ],
      tone: {
        voice_keywords: ['conversational'],
        forbidden_phrases: ['synergy'],
        formatting_rules: ['Short paragraphs'],
      },
      tradeoffs: { autonomy_level: 0.4, accuracy_vs_speed: 0.8, cost_sensitivity: 0.3 },
      evidence_policy: { require_citations_for: ['statistics'], uncertainty_language_rules: [] },
      taboos: { never_do: ['Delete production data'], must_escalate: ['Security incidents'] },
    },
    guardrails: {
      schema_version: 'guardrails.v1',
      permissions: [
        { scope_id: 'fs', tool_ref: 'filesystem:write', resources: ['*'], ops: ['write'] },
      ],
      approvals: [],
      rate_limits: [],
    } as any,
    memory: {
      schema_version: 'memory.v1',
      runtime_target: 'generic',
      stores: [],
      write_policy: {
        salience_rules: [],
        pii_handling: { detect: true, redact: false, store_separately: false },
        update_mode: 'append',
        revisit_triggers: [],
      },
      retention_policy: { ttl_days: 90, prune_strategy: 'oldest' },
    } as any,
    skills: {
      schema_version: 'skills_manifest.v1',
      skills: [
        {
          skill_id: 'code-review',
          name: 'Code Review',
          description: 'Review code quality',
          tags: ['dev'],
          risk_level: 'low',
          required_tools: [],
          compatible_runtimes: ['*'],
        },
      ],
    },
    vocabulary: {
      principles_heading: 'Engineering Standards',
      drift_verb: 'Standards drift',
    },
  };
}

describe('generateClaudeMd', () => {
  it('generates header with TasteKit version', () => {
    const result = generateClaudeMd(fullContext());
    expect(result).toContain('# CLAUDE.md — Generated by TasteKit v1.0.0');
  });

  it('generates footer with regeneration note', () => {
    const result = generateClaudeMd(fullContext());
    expect(result).toContain('Do not edit manually');
    expect(result).toContain('tastekit compile');
  });

  it('includes identity/principles block when constitution provided', () => {
    const result = generateClaudeMd(fullContext());
    expect(result).toContain('Prioritize clarity');
  });

  it('includes skills index block when skills provided', () => {
    const result = generateClaudeMd(fullContext());
    expect(result).toContain('Code Review');
  });

  it('generates non-empty output with minimal context', () => {
    const result = generateClaudeMd({ generator_version: '1.0.0' });
    expect(result).toContain('# CLAUDE.md');
    expect(result.length).toBeGreaterThan(50);
  });

  it('omits blocks that return null for missing data', () => {
    const result = generateClaudeMd({ generator_version: '1.0.0' });
    // Without constitution, guardrails, skills — most blocks return null
    // But header and footer are always present
    expect(result).toContain('# CLAUDE.md');
    expect(result).toContain('---');
  });
});
