import { describe, expect, it } from 'vitest';
import { generateClaudeMd } from '../claude-md-generator.js';
import type { GeneratorContext } from '../types.js';

function fullContext(): GeneratorContext {
  return {
    generator_version: '1.0.0',
    domain_id: 'development-agent',
    constitution: {
      schema_version: 'constitution.v1',
      generated_at: '2026-01-01T00:00:00.000Z',
      generator_version: '1.0.0',
      user_scope: 'single_user',
      principles: [
        { id: 'clarity', statement: 'Prioritize clarity', priority: 1, applies_to: ['*'] },
      ],
      tone: {
        voice_keywords: ['conversational'],
        forbidden_phrases: ['synergy'],
        formatting_rules: ['Short paragraphs'],
      },
      tradeoffs: { autonomy_level: 0.4, accuracy_vs_speed: 0.8, cost_sensitivity: 0.3 },
      evidence_policy: { require_citations_for: ['statistics'], uncertainty_language_rules: [] },
      taboos: { never_do: ['Delete production data'], must_escalate: ['Security incidents'] },
      extensions: {
        'x-tastekit-composition': {
          schema_version: 'tastekit.composition.v1',
          mode: 'operator',
          domain_id: 'development-agent',
          domain_specific: {
            code_review: {
              preferred_focus: 'Lead with correctness and regression risk.',
              raw_transcript: 'Raw transcript should stay out of markdown.',
            },
          },
          dimensions: {
            code_review: {
              dimension_id: 'code_review',
              status: 'covered',
              summary: 'User wants risk-first code review.',
              facts: ['Lead with correctness issues.'],
              source_turns: [1, 2],
            },
          },
        },
      },
    },
    guardrails: {
      schema_version: 'guardrails.v1',
      permissions: [
        { scope_id: 'fs', tool_ref: 'filesystem:write', resources: ['*'], ops: ['write'] },
      ],
      approvals: [],
      rate_limits: [],
    } as any,
    memory: {
      schema_version: 'memory.v1',
      runtime_target: 'generic',
      stores: [],
      write_policy: {
        salience_rules: [],
        pii_handling: { detect: true, redact: false, store_separately: false },
        update_mode: 'append',
        revisit_triggers: [],
      },
      retention_policy: { ttl_days: 90, prune_strategy: 'oldest' },
    } as any,
    skills: {
      schema_version: 'skills_manifest.v1',
      skills: [
        {
          skill_id: 'code-review',
          name: 'Code Review',
          description: 'Review code quality',
          tags: ['dev'],
          risk_level: 'low',
          required_tools: [],
          compatible_runtimes: ['*'],
        },
      ],
    },
    vocabulary: {
      principles_heading: 'Engineering Standards',
      drift_verb: 'Standards drift',
    },
  };
}

describe('generateClaudeMd', () => {
  it('wraps generated content in one TasteKit managed region', () => {
    const result = generateClaudeMd(fullContext());
    expect(result.match(/BEGIN TASTEKIT MANAGED REGION/g)).toHaveLength(1);
    expect(result.match(/END TASTEKIT MANAGED REGION/g)).toHaveLength(1);
  });

  it('generates header with TasteKit version', () => {
    const result = generateClaudeMd(fullContext());
    expect(result).toContain('# CLAUDE.md — Generated by TasteKit v1.0.0');
  });

  it('generates footer with regeneration note', () => {
    const result = generateClaudeMd(fullContext());
    expect(result).toContain('Do not edit manually');
    expect(result).toContain('tastekit compile');
  });

  it('includes identity/principles block when constitution provided', () => {
    const result = generateClaudeMd(fullContext());
    expect(result).toContain('Prioritize clarity');
  });

  it('includes skills index block when skills provided', () => {
    const result = generateClaudeMd(fullContext());
    expect(result).toContain('Code Review');
  });

  it('summarizes composition extension without dumping raw transcript fields', () => {
    const result = generateClaudeMd(fullContext());
    expect(result).toContain('## Taste Composition');
    expect(result).toContain('code_review');
    expect(result).toContain('captured in constitution detail');
    expect(result).not.toContain('Raw transcript should stay out of markdown.');
    expect(result).not.toContain('User wants risk-first code review.');
    expect(result).not.toContain('Lead with correctness and regression risk.');
  });

  it('omits composition facts from runtime markdown', () => {
    const ctx = fullContext();
    const composition = ctx.constitution?.extensions?.['x-tastekit-composition'] as any;
    composition.dimensions.code_review.facts = [
      "Example: 'Hey, I'm not sure if you want me to challenge this plan or just execute on it — which mode?'",
      'Prefer direct, low-friction clarification.',
    ];

    const result = generateClaudeMd(ctx);

    expect(result).toContain('code_review');
    expect(result).not.toContain('Facts:');
    expect(result).not.toContain('User wants risk-first code review.');
    expect(result).not.toContain('Prefer direct, low-friction clarification.');
    expect(result).not.toContain("I'm not sure if you want me to challenge this plan or just execute on it");
  });

  it('omits long quoted interview content from summaries and domain-specific values', () => {
    const ctx = fullContext();
    const composition = ctx.constitution?.extensions?.['x-tastekit-composition'] as any;
    composition.domain_specific.code_review = {
      preferred_focus: 'Lead with correctness and regression risk.',
      example: "Example: 'Hey, I'm not sure if you want me to challenge this plan or just execute on it — which mode?'",
    };
    composition.dimensions.code_review.summary = "User said: 'Hey, I'm not sure if you want me to challenge this plan or just execute on it — which mode?'";
    composition.dimensions.code_review.facts = ['Prefer direct, low-friction clarification.'];

    const result = generateClaudeMd(ctx);

    expect(result).toContain('code_review');
    expect(result).not.toContain('Facts:');
    expect(result).not.toContain('Lead with correctness and regression risk.');
    expect(result).not.toContain('Prefer direct, low-friction clarification.');
    expect(result).not.toContain("I'm not sure if you want me to challenge this plan or just execute on it");
  });

  it('omits raw-ish paraphrased interview facts from runtime markdown', () => {
    const ctx = fullContext();
    const composition = ctx.constitution?.extensions?.['x-tastekit-composition'] as any;
    composition.dimensions.code_review.summary = 'Prioritizes clear rules for when to challenge versus move fast.';
    composition.dimensions.code_review.facts = [
      'The stuff that matters most includes how it decides when to challenge me versus when to move fast and where the hard approval boundaries are.',
      'Challenge intensity is calibrated by reversibility and blast radius.',
    ];

    const result = generateClaudeMd(ctx);

    expect(result).toContain('code_review');
    expect(result).not.toContain('Prioritizes clear rules for when to challenge versus move fast.');
    expect(result).not.toContain('Facts:');
    expect(result).not.toContain('Challenge intensity is calibrated by reversibility and blast radius.');
    expect(result).not.toContain('how it decides when to challenge me versus when to move fast');
  });

  it('omits compact facts that can still match live transcript phrases', () => {
    const ctx = fullContext();
    const composition = ctx.constitution?.extensions?.['x-tastekit-composition'] as any;
    composition.dimensions.code_review.summary = 'User wants crisp autonomy boundaries for reversible work.';
    composition.dimensions.code_review.facts = [
      'Framing should be agentic with crisp approval boundaries.',
      'strong opinions and move fast just not on irreversible things without checking',
    ];

    const result = generateClaudeMd(ctx);

    expect(result).toContain('code_review');
    expect(result).not.toContain('User wants crisp autonomy boundaries for reversible work.');
    expect(result).not.toContain('Facts:');
    expect(result).not.toContain('strong opinions and move fast');
    expect(result).not.toContain('Framing should be agentic');
  });

  it('omits domain-specific fact fields from runtime markdown', () => {
    const ctx = fullContext();
    const composition = ctx.constitution?.extensions?.['x-tastekit-composition'] as any;
    composition.domain_specific.code_review = {
      summary: 'Needs active challenge with final user control.',
      artifact_shape: 'Prefers runnable examples over abstract recommendations.',
      facts: [
        'strong opinions and move fast just not on irreversible things without checking',
      ],
    };

    const result = generateClaudeMd(ctx);

    expect(result).toContain('code_review');
    expect(result).not.toContain('Needs active challenge with final user control.');
    expect(result).not.toContain('artifact_shape: Prefers runnable examples over abstract recommendations.');
    expect(result).not.toContain('facts:');
    expect(result).not.toContain('strong opinions and move fast');
  });

  it('omits long composition summaries that can match live transcript phrases', () => {
    const ctx = fullContext();
    const composition = ctx.constitution?.extensions?.['x-tastekit-composition'] as any;
    composition.domain_specific.core_purpose = {
      summary: 'General-purpose agent for substantive work on high-stakes operator workflows involving research, planning, drafting, and challenging assumptions.',
    };
    composition.dimensions.core_purpose = {
      dimension_id: 'core_purpose',
      status: 'covered',
      summary: 'User needs a general-purpose agent for substantive work on high-stakes operator workflows involving research, planning, drafting, and challenging assumptions.',
    };

    const result = generateClaudeMd(ctx);

    expect(result).toContain('core_purpose');
    expect(result).not.toContain('User needs a general-purpose agent for substantive work');
    expect(result).not.toContain('General-purpose agent for substantive work on high-stakes');
  });

  it('generates non-empty output with minimal context', () => {
    const result = generateClaudeMd({ generator_version: '1.0.0' });
    expect(result).toContain('# CLAUDE.md');
    expect(result.length).toBeGreaterThan(50);
  });

  it('omits blocks that return null for missing data', () => {
    const result = generateClaudeMd({ generator_version: '1.0.0' });
    // Without constitution, guardrails, skills — most blocks return null
    // But header and footer are always present
    expect(result).toContain('# CLAUDE.md');
    expect(result).toContain('---');
  });
});
