/**
 * OpenClaw Adapter
 *
 * Exports TasteKit artifacts to a complete OpenClaw workspace:
 * - SOUL.md (personality, values, tone)
 * - IDENTITY.md (capabilities, role, domain)
 * - AGENTS.md (operational behavior, guardrails, skills)
 * - openclaw.config.json (structured config, backward compatible)
 * - skills/ (AgentSkills-compatible skill directories)
 */

import { TasteKitAdapter, ExportOpts, InstallOpts } from '../adapter-interface.js';
import { readFileSync, writeFileSync, cpSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';
import { createRequire } from 'node:module';
import { resolveArtifactPath, resolveSkillsPath, resolveBindingsPath } from '@actrun_ai/tastekit-core/utils';
import { generateSoulMd, generateAgentsMd, type GeneratorContext } from '@actrun_ai/tastekit-core/generators';

const require = createRequire(import.meta.url);

export class OpenClawAdapter implements TasteKitAdapter {
  id = 'openclaw';
  version = '2.0.0';

  async detect(target: string): Promise<boolean> {
    return existsSync(join(target, 'openclaw.config.json')) ||
      existsSync(join(target, 'AGENTS.md'));
  }

  async export(profilePath: string, outDir: string, opts: ExportOpts): Promise<void> {
    mkdirSync(outDir, { recursive: true });

    const ctx = this.buildContext(profilePath);
    const constitution = ctx.constitution;

    if (!constitution) {
      throw new Error('Constitution not found. Run tastekit compile first.');
    }

    // 1. Generate SOUL.md (personality, values, tone)
    writeFileSync(join(outDir, 'SOUL.md'), generateSoulMd(ctx));

    // 2. Generate IDENTITY.md (capabilities, role, domain)
    writeFileSync(join(outDir, 'IDENTITY.md'), generateIdentityMd(ctx));

    // 3. Generate AGENTS.md (operational behavior, guardrails, skills)
    writeFileSync(join(outDir, 'AGENTS.md'), generateAgentsMd(ctx));

    // 4. Generate openclaw.config.json (structured, backward compatible)
    writeFileSync(
      join(outDir, 'openclaw.config.json'),
      JSON.stringify(generateOpenClawConfig(constitution), null, 2),
    );

    // 5. Copy skills in AgentSkills-compatible format
    if (opts.includeSkills) {
      const skillsPath = resolveSkillsPath(profilePath);
      if (existsSync(skillsPath)) {
        cpSync(skillsPath, join(outDir, 'skills'), { recursive: true });
      }
    }
  }

  async install(outDir: string, target: string, _opts: InstallOpts): Promise<void> {
    cpSync(outDir, target, { recursive: true });
  }

  private buildContext(profilePath: string): GeneratorContext {
    const ctx: GeneratorContext = {
      generator_version: '1.0.0',
    };

    // Constitution
    const constitutionPath = resolveArtifactPath(profilePath, 'constitution');
    if (existsSync(constitutionPath)) {
      ctx.constitution = tryParse(constitutionPath);
    }

    // Guardrails
    const guardrailsPath = resolveArtifactPath(profilePath, 'guardrails');
    if (existsSync(guardrailsPath)) {
      ctx.guardrails = tryParse(guardrailsPath);
    }

    // Memory
    const memoryPath = resolveArtifactPath(profilePath, 'memory');
    if (existsSync(memoryPath)) {
      ctx.memory = tryParse(memoryPath);
    }

    // Skills manifest
    const skillsDir = resolveSkillsPath(profilePath);
    const manifestPath = join(skillsDir, 'manifest.v1.yaml');
    if (existsSync(manifestPath)) {
      ctx.skills = tryParse(manifestPath);
    }

    // Bindings
    const bindingsPath = resolveBindingsPath(profilePath);
    if (existsSync(bindingsPath)) {
      ctx.bindings = tryParse(bindingsPath);
    }

    // Domain config
    const configPath = join(profilePath, 'tastekit.yaml');
    if (existsSync(configPath)) {
      const config = tryParse(configPath);
      ctx.domain_id = config?.domain_id;
    }

    return ctx;
  }
}

// ---------------------------------------------------------------------------
// IDENTITY.md generator
// ---------------------------------------------------------------------------

function generateIdentityMd(ctx: GeneratorContext): string {
  const lines: string[] = [];

  lines.push('# IDENTITY.md');
  lines.push(`<!-- Generated by TasteKit v${ctx.generator_version}. Re-run \`tastekit export --target openclaw\` to regenerate. -->`);
  lines.push('');

  // Role and domain
  lines.push('## Role');
  lines.push('');
  if (ctx.domain_id) {
    const domainLabel = ctx.domain_id.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
    lines.push(`You are a **${domainLabel}** configured via TasteKit.`);
  } else {
    lines.push('You are an AI agent configured via TasteKit.');
  }
  lines.push('');

  // Capabilities from skills
  if (ctx.skills?.skills && ctx.skills.skills.length > 0) {
    lines.push('## Capabilities');
    lines.push('');
    for (const skill of ctx.skills.skills) {
      lines.push(`- **${skill.name}**: ${skill.description}`);
    }
    lines.push('');
  }

  // Tools from bindings
  if (ctx.bindings?.servers && ctx.bindings.servers.length > 0) {
    lines.push('## Tools');
    lines.push('');
    for (const server of ctx.bindings.servers) {
      lines.push(`### ${server.name}`);
      if (server.tools && server.tools.length > 0) {
        for (const tool of server.tools) {
          const risk = tool.risk_hints?.length ? ` (risk: ${tool.risk_hints.join(', ')})` : '';
          lines.push(`- \`${tool.tool_ref}\`${risk}`);
        }
      }
      lines.push('');
    }
  }

  // Autonomy level
  if (ctx.constitution?.tradeoffs?.autonomy_level !== undefined) {
    const level = ctx.constitution.tradeoffs.autonomy_level;
    let description: string;
    if (level < 0.3) description = 'Conservative. Ask before most actions.';
    else if (level < 0.7) description = 'Balanced. Act on safe operations, ask for risky ones.';
    else description = 'High autonomy. Act independently, escalate only for destructive operations.';

    lines.push('## Autonomy');
    lines.push('');
    lines.push(`Level: ${level} — ${description}`);
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by TasteKit v${ctx.generator_version} on ${new Date().toISOString().split('T')[0]}*`);
  lines.push('');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// openclaw.config.json generator (backward compatible)
// ---------------------------------------------------------------------------

function generateOpenClawConfig(constitution: any): any {
  return {
    version: '1.0',
    profile: {
      principles: constitution.principles,
      tone: constitution.tone,
      tradeoffs: constitution.tradeoffs,
    },
    behavior: {
      autonomy_level: constitution.tradeoffs?.autonomy_level,
      require_citations: constitution.evidence_policy?.require_citations_for,
    },
    safety: {
      forbidden_phrases: constitution.tone?.forbidden_phrases,
      taboos: constitution.taboos,
    },
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function tryParse(filePath: string): any {
  const content = readFileSync(filePath, 'utf-8');
  try {
    return JSON.parse(content);
  } catch { /* not JSON */ }
  try {
    const YAML = require('yaml');
    return YAML.parse(content);
  } catch { /* skip */ }
  return null;
}
