/**
 * AGENTS.md Generator
 *
 * Generates an AGENTS.md from compiled TasteKit artifacts.
 * AGENTS.md is the AAIF standard for agent operational config.
 */

import type { GeneratorContext } from './types.js';

export function generateAgentsMd(ctx: GeneratorContext): string {
  const lines: string[] = [];

  lines.push('# AGENTS.md');
  lines.push(`<!-- Generated by TasteKit v${ctx.generator_version}. Re-run \`tastekit compile\` to regenerate. -->`);
  lines.push('');

  if (ctx.constitution?.principles && ctx.constitution.principles.length > 0) {
    lines.push('## Principles');
    lines.push('');
    for (const p of ctx.constitution.principles) {
      lines.push(`- **${p.id}**: ${p.statement}`);
    }
    lines.push('');
  }

  if (ctx.guardrails?.permissions) {
    lines.push('## Guardrails');
    lines.push('');
    for (const perm of ctx.guardrails.permissions as unknown as Array<{ action: string; allowed: boolean; requires_approval?: boolean }>) {
      lines.push(`- ${perm.action}: ${perm.allowed ? 'allowed' : 'denied'}${perm.requires_approval ? ' (requires approval)' : ''}`);
    }
    lines.push('');
  }

  if (ctx.constitution?.tone) {
    const tone = ctx.constitution.tone;
    lines.push('## Tone & Voice');
    lines.push('');
    if (tone.voice_keywords && tone.voice_keywords.length > 0) {
      lines.push(`Voice: ${tone.voice_keywords.join(', ')}`);
    }
    if (tone.forbidden_phrases && tone.forbidden_phrases.length > 0) {
      lines.push('');
      lines.push('Avoid:');
      for (const phrase of tone.forbidden_phrases) {
        lines.push(`- "${phrase}"`);
      }
    }
    lines.push('');
  }

  if (ctx.constitution?.tradeoffs?.autonomy_level !== undefined) {
    lines.push('## Behavior');
    lines.push('');
    lines.push(`Autonomy level: ${ctx.constitution.tradeoffs.autonomy_level}`);
    lines.push('');
  }

  if (ctx.constitution?.taboos?.never_do && ctx.constitution.taboos.never_do.length > 0) {
    lines.push('## Restrictions');
    lines.push('');
    for (const taboo of ctx.constitution.taboos.never_do) {
      lines.push(`- ${taboo}`);
    }
    lines.push('');
  }

  if (ctx.skills?.skills && ctx.skills.skills.length > 0) {
    lines.push('## Skills');
    lines.push('');
    for (const skill of ctx.skills.skills) {
      lines.push(`- **${skill.name}** (\`${skill.skill_id}\`): ${skill.description}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by TasteKit v${ctx.generator_version} on ${new Date().toISOString().split('T')[0]}*`);
  lines.push('');

  return lines.join('\n');
}
