/**
 * AGENTS.md Generator
 *
 * Generates an AGENTS.md from compiled TasteKit artifacts.
 * AGENTS.md is the AAIF standard for agent operational config.
 */

import type { GeneratorContext } from './types.js';
import { renderManagedRegion } from './managed-region.js';
import { tasteCompositionBlock } from './blocks/taste-composition.js';
import { metacognitionBlock } from './blocks/metacognition.js';

export function generateAgentsMd(ctx: GeneratorContext): string {
  const lines: string[] = [];

  lines.push('# AGENTS.md');
  lines.push(`<!-- Generated by TasteKit v${ctx.generator_version}. Re-run \`tastekit compile\` to regenerate. -->`);
  lines.push('');

  if (ctx.constitution?.principles && ctx.constitution.principles.length > 0) {
    lines.push('## Principles');
    lines.push('');
    for (const p of ctx.constitution.principles) {
      lines.push(`- **${p.id}**: ${p.statement}`);
    }
    lines.push('');
  }

  if (ctx.guardrails?.permissions && ctx.guardrails.permissions.length > 0) {
    lines.push('## Guardrails');
    lines.push('');
    lines.push('### Permissions');
    for (const perm of ctx.guardrails.permissions) {
      const ops = perm.ops.join('/');
      const resources = perm.resources.length > 0 ? perm.resources.join(', ') : '*';
      lines.push(`- \`${perm.tool_ref}\` (${ops}) on \`${resources}\` — scope: \`${perm.scope_id}\``);
    }
    lines.push('');
  }

  if (ctx.guardrails?.approvals && ctx.guardrails.approvals.length > 0) {
    if (!ctx.guardrails.permissions || ctx.guardrails.permissions.length === 0) {
      lines.push('## Guardrails');
      lines.push('');
    }
    lines.push('### Approval rules');
    for (const rule of ctx.guardrails.approvals) {
      lines.push(`- **${rule.rule_id}**: When ${rule.when} → ${rule.action} (via ${rule.channel})`);
    }
    lines.push('');
  }

  if (ctx.guardrails?.rate_limits && ctx.guardrails.rate_limits.length > 0) {
    if (
      (!ctx.guardrails.permissions || ctx.guardrails.permissions.length === 0) &&
      (!ctx.guardrails.approvals || ctx.guardrails.approvals.length === 0)
    ) {
      lines.push('## Guardrails');
      lines.push('');
    }
    lines.push('### Rate limits');
    for (const rl of ctx.guardrails.rate_limits) {
      lines.push(`- \`${rl.tool_ref}\` — max ${rl.limit}/${rl.window}`);
    }
    lines.push('');
  }

  if (ctx.constitution?.tone) {
    const tone = ctx.constitution.tone;
    lines.push('## Tone & Voice');
    lines.push('');
    if (tone.voice_keywords && tone.voice_keywords.length > 0) {
      lines.push(`Voice: ${tone.voice_keywords.join(', ')}`);
    }
    if (tone.forbidden_phrases && tone.forbidden_phrases.length > 0) {
      lines.push('');
      lines.push('Avoid:');
      for (const phrase of tone.forbidden_phrases) {
        lines.push(`- "${phrase}"`);
      }
    }
    lines.push('');
  }

  if (ctx.constitution?.tradeoffs?.autonomy_level !== undefined) {
    lines.push('## Behavior');
    lines.push('');
    lines.push(`Autonomy level: ${ctx.constitution.tradeoffs.autonomy_level}`);
    lines.push('');
  }

  if (ctx.constitution?.taboos?.never_do && ctx.constitution.taboos.never_do.length > 0) {
    lines.push('## Restrictions');
    lines.push('');
    for (const taboo of ctx.constitution.taboos.never_do) {
      lines.push(`- ${taboo}`);
    }
    lines.push('');
  }

  if (ctx.skills?.skills && ctx.skills.skills.length > 0) {
    lines.push('## Skills');
    lines.push('');
    for (const skill of ctx.skills.skills) {
      lines.push(`- **${skill.name}** (\`${skill.skill_id}\`): ${skill.description}`);
    }
    lines.push('');
  }

  const tasteComposition = tasteCompositionBlock(ctx);
  if (tasteComposition) {
    lines.push(tasteComposition);
    lines.push('');
  }

  const metacognition = metacognitionBlock(ctx);
  if (metacognition) {
    lines.push(metacognition);
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by TasteKit v${ctx.generator_version} on ${new Date().toISOString().split('T')[0]}*`);
  lines.push('');

  return renderManagedRegion(lines.join('\n'));
}
