/**
 * AGENTS.md Generator
 *
 * Generates an AGENTS.md from compiled TasteKit artifacts.
 * AGENTS.md is the AAIF standard for agent operational config.
 */

import type { GeneratorContext } from './types.js';

export function generateAgentsMd(ctx: GeneratorContext): string {
  const lines: string[] = [];
  const permissions = ctx.guardrails?.permissions ?? [];
  const approvals = ctx.guardrails?.approvals ?? [];
  const rateLimits = ctx.guardrails?.rate_limits ?? [];

  lines.push('# AGENTS.md');
  lines.push(`<!-- Generated by TasteKit v${ctx.generator_version}. Re-run \`tastekit compile\` to regenerate. -->`);
  lines.push('');

  if (ctx.constitution?.principles && ctx.constitution.principles.length > 0) {
    lines.push('## Principles');
    lines.push('');
    for (const p of ctx.constitution.principles) {
      lines.push(`- **${p.id}**: ${p.statement}`);
    }
    lines.push('');
  }

  if (permissions.length > 0 || approvals.length > 0 || rateLimits.length > 0) {
    lines.push('## Guardrails');
    lines.push('');
    for (const perm of permissions) {
      const details: string[] = [];

      if (perm.ops.length > 0) {
        details.push(perm.ops.join(', '));
      }

      if (perm.resources.length > 0) {
        details.push(`resources: ${perm.resources.join(', ')}`);
      }

      const suffix = details.length > 0 ? ` (${details.join('; ')})` : '';
      lines.push(`- ${perm.tool_ref}: allowed${suffix}`);
    }

    for (const rule of approvals) {
      lines.push(`- ${rule.rule_id}: ${rule.action} when ${rule.when} via ${rule.channel}`);
    }

    for (const limit of rateLimits) {
      lines.push(`- ${limit.tool_ref}: max ${limit.limit}/${limit.window}`);
    }
    lines.push('');
  }

  if (ctx.constitution?.tone) {
    const tone = ctx.constitution.tone;
    lines.push('## Tone & Voice');
    lines.push('');
    if (tone.voice_keywords && tone.voice_keywords.length > 0) {
      lines.push(`Voice: ${tone.voice_keywords.join(', ')}`);
    }
    if (tone.forbidden_phrases && tone.forbidden_phrases.length > 0) {
      lines.push('');
      lines.push('Avoid:');
      for (const phrase of tone.forbidden_phrases) {
        lines.push(`- "${phrase}"`);
      }
    }
    lines.push('');
  }

  if (ctx.constitution?.tradeoffs?.autonomy_level !== undefined) {
    lines.push('## Behavior');
    lines.push('');
    lines.push(`Autonomy level: ${ctx.constitution.tradeoffs.autonomy_level}`);
    lines.push('');
  }

  if (ctx.constitution?.taboos?.never_do && ctx.constitution.taboos.never_do.length > 0) {
    lines.push('## Restrictions');
    lines.push('');
    for (const taboo of ctx.constitution.taboos.never_do) {
      lines.push(`- ${taboo}`);
    }
    lines.push('');
  }

  if (ctx.skills?.skills && ctx.skills.skills.length > 0) {
    lines.push('## Skills');
    lines.push('');
    for (const skill of ctx.skills.skills) {
      lines.push(`- **${skill.name}** (\`${skill.skill_id}\`): ${skill.description}`);
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by TasteKit v${ctx.generator_version} on ${new Date().toISOString().split('T')[0]}*`);
  lines.push('');

  return lines.join('\n');
}
