/**
 * CLAUDE.md Generator
 *
 * Assembles a compositional CLAUDE.md from generator blocks.
 * Each block is a pure function: (ctx) => string | null.
 */

import type { GeneratorContext, GeneratorBlock } from './types.js';

// Mandatory blocks (always included when data exists)
import { identityBlock } from './blocks/identity.js';
import { guardrailsBlock } from './blocks/guardrails.js';
import { skillsIndexBlock } from './blocks/skills-index.js';
import { sessionRhythmBlock } from './blocks/session-rhythm.js';
import { memoryPolicyBlock } from './blocks/memory-policy.js';
import { toolUsageBlock } from './blocks/tool-usage.js';
import { driftAwarenessBlock } from './blocks/drift-awareness.js';

// Conditional blocks (included based on config)
import { domainContextBlock } from './blocks/domain-context.js';
import { playbookIndexBlock } from './blocks/playbook-index.js';
import { vocabularyBlock } from './blocks/vocabulary.js';
import { evaluationCriteriaBlock } from './blocks/evaluation-criteria.js';

/**
 * Ordered list of all blocks. Dependency order matters:
 * identity first (core context), then guardrails, then domain-specific,
 * then operational (skills, tools, memory), then meta (drift, eval).
 */
const BLOCKS: GeneratorBlock[] = [
  identityBlock,
  guardrailsBlock,
  domainContextBlock,
  skillsIndexBlock,
  toolUsageBlock,
  memoryPolicyBlock,
  sessionRhythmBlock,
  driftAwarenessBlock,
  playbookIndexBlock,
  vocabularyBlock,
  evaluationCriteriaBlock,
];

/**
 * Generate a complete CLAUDE.md from compiled TasteKit artifacts.
 */
export function generateClaudeMd(ctx: GeneratorContext): string {
  const sections: string[] = [];

  // Header
  sections.push(`# CLAUDE.md — Generated by TasteKit v${ctx.generator_version}`);
  sections.push('');

  // Run each block
  for (const block of BLOCKS) {
    const section = block(ctx);
    if (section) {
      sections.push(section);
      sections.push('');
    }
  }

  // Footer
  sections.push('---');
  sections.push(`_Generated by TasteKit v${ctx.generator_version}. Do not edit manually — re-run \`tastekit compile\` to regenerate._`);
  sections.push('');

  return sections.join('\n');
}
