/**
 * SOUL.md Generator
 *
 * Generates a human-readable SOUL.md from compiled TasteKit constitution.
 * SOUL.md is the winning convention for agent personality/identity.
 */

import type { GeneratorContext } from './types.js';

export function generateSoulMd(ctx: GeneratorContext): string {
  const lines: string[] = [];

  lines.push('# SOUL.md');
  lines.push(`<!-- Generated by TasteKit v${ctx.generator_version}. Re-run \`tastekit compile\` to regenerate. -->`);
  lines.push('');

  if (ctx.domain_id) {
    lines.push('## Identity');
    lines.push('');
    lines.push(`Domain: ${ctx.domain_id}`);
    lines.push('');
  }

  if (ctx.constitution?.principles && ctx.constitution.principles.length > 0) {
    lines.push('## Principles');
    lines.push('');
    for (const p of ctx.constitution.principles) {
      const rationale = p.rationale ? ` — ${p.rationale}` : '';
      lines.push(`${p.priority}. **${p.statement}**${rationale}`);
    }
    lines.push('');
  }

  if (ctx.constitution?.tone) {
    const tone = ctx.constitution.tone;
    lines.push('## Voice & Tone');
    lines.push('');
    if (tone.voice_keywords && tone.voice_keywords.length > 0) {
      lines.push(`Keywords: ${tone.voice_keywords.join(', ')}`);
    }
    if (tone.forbidden_phrases && tone.forbidden_phrases.length > 0) {
      lines.push('');
      lines.push('Avoid:');
      for (const phrase of tone.forbidden_phrases) {
        lines.push(`- "${phrase}"`);
      }
    }
    if (tone.formatting_rules && tone.formatting_rules.length > 0) {
      lines.push('');
      lines.push('Formatting:');
      for (const rule of tone.formatting_rules) {
        lines.push(`- ${rule}`);
      }
    }
    lines.push('');
  }

  if (ctx.constitution?.tradeoffs) {
    const t = ctx.constitution.tradeoffs;
    lines.push('## Tradeoffs');
    lines.push('');
    if (t.autonomy_level !== undefined) {
      lines.push(`- Autonomy: ${t.autonomy_level} (0=always ask, 1=fully autonomous)`);
    }
    if (t.accuracy_vs_speed !== undefined) {
      lines.push(`- Accuracy vs Speed: ${t.accuracy_vs_speed} (0=speed first, 1=accuracy first)`);
    }
    if (t.cost_sensitivity !== undefined) {
      lines.push(`- Cost Sensitivity: ${t.cost_sensitivity} (0=ignore cost, 1=minimize cost)`);
    }
    lines.push('');
  }

  if (ctx.constitution?.taboos) {
    const taboos = ctx.constitution.taboos;
    if (taboos.never_do && taboos.never_do.length > 0) {
      lines.push('## Taboos');
      lines.push('');
      lines.push('Never:');
      for (const item of taboos.never_do) {
        lines.push(`- ${item}`);
      }
      if (taboos.must_escalate && taboos.must_escalate.length > 0) {
        lines.push('');
        lines.push('Must escalate:');
        for (const item of taboos.must_escalate) {
          lines.push(`- ${item}`);
        }
      }
      lines.push('');
    }
  }

  if (ctx.constitution?.evidence_policy) {
    const ep = ctx.constitution.evidence_policy;
    lines.push('## Evidence Policy');
    lines.push('');
    if (ep.require_citations_for && ep.require_citations_for.length > 0) {
      lines.push(`Require citations for: ${ep.require_citations_for.join(', ')}`);
    }
    if (ep.uncertainty_language_rules && ep.uncertainty_language_rules.length > 0) {
      lines.push('');
      for (const rule of ep.uncertainty_language_rules) {
        lines.push(`- ${rule}`);
      }
    }
    lines.push('');
  }

  lines.push('---');
  lines.push(`*Generated by TasteKit v${ctx.generator_version} on ${new Date().toISOString().split('T')[0]}*`);
  lines.push('');

  return lines.join('\n');
}
