/**
 * ActRun Autopilots Adapter
 *
 * Exports TasteKit artifacts to ActRun Autopilots format.
 * Uses the Agent Skills standard (agentskills.io) for skills.
 * Also generates autopilots.yaml for backward compatibility.
 */

import { TasteKitAdapter, ExportOpts, InstallOpts } from '../adapter-interface.js';
import { readFileSync, writeFileSync, existsSync, cpSync, mkdirSync } from 'fs';
import { join } from 'path';
import { createRequire } from 'node:module';
import { resolveArtifactPath, resolveSkillsPath } from '@tastekit/core/utils';

const require = createRequire(import.meta.url);

export class AutopilotsAdapter implements TasteKitAdapter {
  id = 'autopilots';
  version = '2.0.0';

  async detect(target: string): Promise<boolean> {
    return existsSync(join(target, 'autopilots.yaml')) ||
      existsSync(join(target, '.agents', 'skills'));
  }

  async export(profilePath: string, outDir: string, opts: ExportOpts): Promise<void> {
    mkdirSync(outDir, { recursive: true });

    const constitutionPath = resolveArtifactPath(profilePath, 'constitution');
    if (!existsSync(constitutionPath)) {
      throw new Error('Constitution not found. Run tastekit compile first.');
    }

    const constitution = JSON.parse(readFileSync(constitutionPath, 'utf-8'));

    // 1. Generate autopilots.yaml (backward compatible)
    writeFileSync(join(outDir, 'autopilots.yaml'), generateAutopilotsYAML(constitution));

    // 2. Copy skills in Agent Skills format (.agents/skills/ convention)
    if (opts.includeSkills) {
      const skillsPath = resolveSkillsPath(profilePath);
      if (existsSync(skillsPath)) {
        const destSkills = join(outDir, '.agents', 'skills');
        mkdirSync(destSkills, { recursive: true });
        cpSync(skillsPath, destSkills, { recursive: true });
      }
    }
  }

  async install(outDir: string, target: string, _opts: InstallOpts): Promise<void> {
    cpSync(outDir, target, { recursive: true });
  }
}

function generateAutopilotsYAML(constitution: any): string {
  return `# ActRun Autopilots Configuration (Generated by TasteKit)
# Skills are in .agents/skills/ (Agent Skills standard)

principles:
${(constitution.principles || []).map((p: any) => `  - id: ${p.id}
    statement: "${(p.statement || '').replace(/"/g, '\\"')}"
    priority: ${p.priority}`).join('\n')}

tone:
  voice_keywords: [${(constitution.tone?.voice_keywords || []).map((k: string) => `"${k}"`).join(', ')}]
  forbidden_phrases: [${(constitution.tone?.forbidden_phrases || []).map((p: string) => `"${p}"`).join(', ')}]

tradeoffs:
  accuracy_vs_speed: ${constitution.tradeoffs?.accuracy_vs_speed ?? 0.5}
  cost_sensitivity: ${constitution.tradeoffs?.cost_sensitivity ?? 0.5}
  autonomy_level: ${constitution.tradeoffs?.autonomy_level ?? 0.5}

taboos:
  never_do: [${(constitution.taboos?.never_do || []).map((t: string) => `"${t.replace(/"/g, '\\"')}"`).join(', ')}]
  must_escalate: [${(constitution.taboos?.must_escalate || []).map((t: string) => `"${t.replace(/"/g, '\\"')}"`).join(', ')}]
`;
}
